# Generated by Django 2.2.5 on 2020-01-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board1',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('gene', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('word', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
