# Generated by Django 2.2.5 on 2020-01-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member1',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gen', models.IntegerField()),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
