# Generated by Django 3.0.2 on 2020-01-20 04:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member1',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gen', models.IntegerField()),
                ('regdate', models.DateField(auto_now_add=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
