# Generated by Django 3.0.2 on 2020-01-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member1',
            old_name='regdate',
            new_name='joindate',
        ),
    ]
